name = "glazed"
version = "0.1.0"
licences = ["MIT"]
description = ""
repository = { type = "github", user = "aslilac", repo = "glazed" }

[dependencies]
gleam_stdlib = "~> 0.25"

[dev-dependencies]
gleeunit = "~> 0.7"
